"use strict";
exports.__esModule = true;
var Auto_1 = require("./Auto");
var AutoCarrera_1 = require("./AutoCarrera");
console.log("Creando Auto");
var miAuto = new Auto_1["default"]("Fiat", "Palio");
console.log(miAuto);
console.log("\nAcelerando Auto");
miAuto.acelerar();
console.log(miAuto);
console.log("");
var miAutoDeCarrera = new AutoCarrera_1["default"]("Ford", "Fiesta", 10);
console.log("Creando Auto de Carrera");
console.log(miAutoDeCarrera);
console.log("\nAcelerando Auto de Carrera");
miAutoDeCarrera.acelerar();
console.log(miAutoDeCarrera);
console.log("\nAgregando Sponsor");
miAutoDeCarrera.agregarSponsor("Shell");
console.log(miAutoDeCarrera);
console.log("\nAgregando Sponsor");
miAutoDeCarrera.agregarSponsor("Mercado Tito");
console.log(miAutoDeCarrera);
console.log("\nAgregando Sponsor repetido");
miAutoDeCarrera.agregarSponsor("Mercado Tito");
console.log(miAutoDeCarrera);
console.log("\nEliminando Sponsor");
miAutoDeCarrera.eliminarSponsor("Mercado Tito");
console.log(miAutoDeCarrera);
console.log("\nEliminando Sponsor que no existe");
miAutoDeCarrera.eliminarSponsor("Mercado Tito");
console.log(miAutoDeCarrera);
console.log("\ncambiando numero de Competencia");
miAutoDeCarrera.cambiarNumero(15);
console.log(miAutoDeCarrera);
